path:
  ckpt_path: "./output/ckpt/VLSP-full"
  log_path: "./output/log/VLSP-full"
  result_path: "./output/result/VLSP-full"
optimizer:
  batch_size: 16
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 3000
  anneal_steps: [5000, 9000, 17000]
  anneal_rate: 0.3
step:
  total_step: 30000
  log_step: 100
  synth_step: 1000
  val_step: 500000
  save_step: 1000
